name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Verify version consistency
      run: |
        MANIFEST_VERSION=$(grep '"version"' custom_components/gecko_spa/manifest.json | cut -d'"' -f4)
        if [ "$MANIFEST_VERSION" != "${{ steps.version.outputs.VERSION }}" ]; then
          echo "Version mismatch: tag=${{ steps.version.outputs.VERSION }}, manifest=$MANIFEST_VERSION"
          exit 1
        fi
        
    - name: Create release archive
      run: |
        # Create ZIP file with the contents of custom_components/gecko_spa
        # HACS will extract this to custom_components/gecko_spa/
        cd custom_components/gecko_spa
        zip -r ../../gecko_spa.zip .
        
    - name: Generate changelog for release
      id: changelog
      run: |
        # Extract changelog for this version
        sed -n '/^### v${{ steps.version.outputs.VERSION }}/,/^### v/p' CHANGELOG.md | head -n -1 > release_notes.md
        if [ ! -s release_notes.md ]; then
          echo "Release notes for version ${{ steps.version.outputs.VERSION }}" > release_notes.md
          echo "" >> release_notes.md
          echo "See CHANGELOG.md for details." >> release_notes.md
        fi
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        name: Gecko InTouch3 HA Integration v${{ steps.version.outputs.VERSION }}
        body_path: release_notes.md
        draft: false
        prerelease: false
        files: gecko_spa.zip